### ISSUE TITLE
Paystack SDK causes error in "react-native-custom-tabs"

### ISSUE THREAD

**Issue by lateef4web** [tolu360/react-native-paystack#1]
Hi @tolu360 ! and thanks for this module, is very useful.
I have been using "react-native-custom-tabs" in my project, it's an Inapp-browser.
When i installed paystack sdk in my project, I have this error as shown below, whenever i tried to launch the Inapp browser;

![screenshot_2017-03-31-00-06-46](https://cloud.githubusercontent.com/assets/13805954/24529985/f1c456f8-15a6-11e7-80e3-01376552bef7.png)

Please help!

**Comment by ibrahimlawal** [comment]
Hello @lateef4web Do you have the error message of what caused the crash?

**Comment by tolu360** [comment]
Hi @lateef4web, did you manage to get things working for you already? It looks like an issue with `react-native-custom-tabs` to me. To be certain, how did you pull in `react-native-paystack`? If you used the `react-native link` command, review your setup and match against the manual installation (see the README)- the link command has been known to fail from time to time.

If everything is in order and the issue persists, remove `react-native-paystack` totally from your project and ensure your project builds and works properly without it before adding it back in. Would expect some feedback. Cheers

**Comment by ibrahimlawal** [comment]
Hello @tolu360,

After a short skype session @lateef4web was able to get it to work fine:

2 things we did differently:

1. We enabled Keychain access on the app before adding Paystack.
2. We used the released version instead of the one available on Dropbox.
