### ISSUE TITLE
Update your Android build tools and environment to v27+

### ISSUE THREAD

**Issue by SirPhemmiey** [tolu360/react-native-paystack#12]
@tolu360 Please must i use ` compileSdkVersion 27 and
    buildToolsVersion "27.0.0"` so as to use the  paystack library effectively?
Cos i am having issues with generating my APK and one of the solutions is to modify `compileSdkVersion 26
buildToolsVersion "26.0.1"`

**Comment by tolu360** [comment]
Yes, the underlying Paystack SDK is dependent on the availability of the `Android SDK Platform-Tools` v27+ and the `Android SDK Tools` v27+ in your local development environment. Even if you choose to set `compileSdkVersion` and `buildToolsVersion` to the least version (26+) supported for Gradle Plugin v3.0 in your project, you still need to have the versions of the build tools mentioned above to build issue-free.

I hinted at [how you can upgrade your project to use Gradle Plugin v3.0](https://github.com/tolu360/react-native-paystack#more-config-android-v314) in the readme

**Comment by SirPhemmiey** [comment]
Alright. Thanks
