### ISSUE TITLE
Enable metadata support for Android

### ISSUE THREAD

**Issue by steveamaza** [tolu360/react-native-paystack#14]
The paystack-android library has support for metadata but the react-native plugin does not recognize metadata for Android (I think it recognizes for iOS if I read the code right).

Enabling metadata support will be helpful for a lot of integrations

```chargeCard() {
    RNPaystack.chargeCard({
        cardNumber: '4123450131001381', 
        expiryMonth: '10', 
        expiryYear: '17', 
        cvc: '883',
        email: 'chargeIOS@master.dev',
        amountInKobo: 150000,
        metadata: {
        custom_fields: [
          {
            value: "Payment From Android",
            display_name: "Payment From Android",
            variable_name: "payment_from_android"
          }
        ]
       }
    })

**Comment by tolu360** [comment]
I would accept a good PR for it, cheers!

**Comment by tolu360** [comment]
In the works!

**Comment by olujedai** [comment]
Any update on this?

**Comment by nlabofa** [comment]
+1

**Comment by AregbesolaOJ** [comment]
Hello @tolu360 please i'd love to know if there's any update on this yet. Thanks

**Comment by Devmaleeq** [comment]
This feature is really important.
I was expecting the react-native package can do everything the reactJS does (including sending metadata)
