### ISSUE TITLE
E_Transaction_Error

### ISSUE THREAD

**Issue by jinaddavid** [tolu360/react-native-paystack#16]
hi @tolu360  i was trying to integrate paystack to my react native app, i follow all the necessary steps 

But when am trying to make payment , the response i receive was  

> trx_...... concluded with error, unable to process transaction.
this are some of the card details i used

Card Number: 5078 5078 5078 5078 12 (Verve)
Expiry Date: any date in the future
CVV: 081
PIN: 1111

expiryMonth:'12',
      expiryYear:'19',
      cardNumber:'4123450131001381',
      cvc:'883',

Please i dont know if am doing anything wrong or the card details are wrong

**Comment by steveamaza** [comment]
@jinaddavid this is not an issue with the plugin. The transaction is failing because most banks are down at this moment. You can try again in an hour or so

**Comment by jinaddavid** [comment]
@steveamaza  thanks for the response,  but up till now the error message still remain the same. 
Any other help?

**Comment by SirPhemmiey** [comment]
@jinaddavid are you using a live public key from paystack or a test public key?

**Comment by jinaddavid** [comment]
Am using a live public key from my account on paystack

**Comment by jinaddavid** [comment]
it works now, am using live public key for test mode instead of test keys
