### ISSUE TITLE
Error: undefined is not an object (evaluating 'RNPaystackNative.chargeCardWithAccessCode')

### ISSUE THREAD

**Issue by Ayo-David** [tolu360/react-native-paystack#17]
Hello @tolu360, please I'm having this error and couldn't resolve it yet. I'm using react native v0.55.3 Your help is well appreciated. Thank you

> undefined is not an object (evaluating 'RNPaystackNative.chargeCardWithAccessCode')
chargeCardWithAccessCode
    c:\dc\react2\icobaw\node_modules\react-native-paystack\index.js:22:26
chargeCardAccess
    c:\dc\react2\icobaw\src\pages\tabPages\paystack.js:27:40
touchableHandlePress
    c:\dc\react2\icobaw\node_modules\react-native\Libraries\Components\Touchable\TouchableOpacity.js:201:45
_performSideEffectsForTransition
    c:\dc\react2\icobaw\node_modules\react-native\Libraries\Components\Touchable\Touchable.js:744:34
_receiveSignal
    c:\dc\react2\icobaw\node_modules\react-native\Libraries\Components\Touchable\Touchable.js:662:44
touchableHandleResponderRelease
    c:\dc\react2\icobaw\node_modules\react-native\Libraries\Components\Touchable\Touchable.js:431:24
invokeGuardedCallback
    c:\dc\react2\icobaw\node_modules\react-native\Libraries\Renderer\ReactNativeRenderer-dev.js:39:15
invokeGuardedCallback
    c:\dc\react2\icobaw\node_modules\react-native\Libraries\Renderer\ReactNativeRenderer-dev.js:221:34
invokeGuardedCallbackAndCatchFirstError
    c:\dc\react2\icobaw\node_modules\react-native\Libraries\Renderer\ReactNativeRenderer-dev.js:245:48
executeDispatch
    c:\dc\react2\icobaw\node_modules\react-native\Libraries\Renderer\ReactNativeRenderer-dev.js:572:4
executeDispatchesInOrder
    c:\dc\react2\icobaw\node_modules\react-native\Libraries\Renderer\ReactNativeRenderer-dev.js:603:20
executeDispatchesAndRelease
    c:\dc\react2\icobaw\node_modules\react-native\Libraries\Renderer\ReactNativeRenderer-dev.js:761:29
executeDispatchesAndReleaseTopLevel
    c:\dc\react2\icobaw\node_modules\react-native\Libraries\Renderer\ReactNativeRenderer-dev.js:772:37
forEachAccumulated
    c:\dc\react2\icobaw\node_modules\react-native\Libraries\Renderer\ReactNativeRenderer-dev.js:740:16
runEventsInBatch
    c:\dc\react2\icobaw\node_modules\react-native\Libraries\Renderer\ReactNativeRenderer-dev.js:927:6
runExtractedEventsInBatch
    c:\dc\react2\icobaw\node_modules\react-native\Libraries\Renderer\ReactNativeRenderer-dev.js:952:19
<unknown>
    c:\dc\react2\icobaw\node_modules\react-native\Libraries\Renderer\ReactNativeRenderer-dev.js:2703:6
batchedUpdates
    c:\dc\react2\icobaw\node_modules\react-native\Libraries\Renderer\ReactNativeRenderer-dev.js:13724:16
batchedUpdates
    c:\dc\react2\icobaw\node_modules\react-native\Libraries\Renderer\ReactNativeRenderer-dev.js:2565:27
_receiveRootNodeIDEvent
    c:\dc\react2\icobaw\node_modules\react-native\Libraries\Renderer\ReactNativeRenderer-dev.js:2701:17
receiveTouches
    c:\dc\react2\icobaw\node_modules\react-native\Libraries\Renderer\ReactNativeRenderer-dev.js:2777:28
__callFunction
    c:\dc\react2\icobaw\node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:351:47
<unknown>
    c:\dc\react2\icobaw\node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:116:26
__guardSafe
    c:\dc\react2\icobaw\node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:314:6
callFunctionReturnFlushedQueue
    c:\dc\react2\icobaw\node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:115:17

**Comment by tolu360** [comment]
Update to the latest version, 3.2.0+ and be sure to go over the breaking changes stated in the README. If you still have this issue on the latest release, open a new issue after the updates. Cheers!
