### ISSUE TITLE
How do I PayStack Split Payment with the Old method of PaystackAndroid OR HOW DO I DO IT with the NEW METHOD

### ISSUE THREAD

**Issue by jerryheir** [tolu360/react-native-paystack#19]
Hi, Please I am under pressure to implement a payment method an app I just completed. It requires split payment... I don't understand some parts of the current documentation. From the Old docs.md , I understand how to get a token but the new documentation is not very clear. Does "access_code" MEAN "token"
From my experience with stripe, I understand Public Key, and Token
I can see how to use the public key, but I don't understand how to get a token and how to get a subAccount code for the split payment...

PLEASE HELP!!! I have no experience with using the popular paystack platform

Please I want to know before I go ahead to create an account on Paystack

**Comment by steveamaza** [comment]
Please see https://developers.paystack.co/v2.0/docs/split-payments.

**Comment by jerryheir** [comment]
Thanks. I have read that. What about the access code

**Comment by steveamaza** [comment]
You get an `access_code` as a response for initializing a transaction. https://developers.paystack.co/reference#initialize-a-transaction

**Comment by jerryheir** [comment]
Okay. Thanks a lot.. So therefore access_code is just like the "token" that
I can save in the database

**Comment by steveamaza** [comment]
No, you are not meant to. A new one is generated per transaction

**Comment by gabrielAhiataku** [comment]
How do I verify a split payment to get charge.success value from JSON
