### ISSUE TITLE
BUILD FAILED on ios

### ISSUE THREAD

**Issue by gbenga504** [tolu360/react-native-paystack#21]
on ios, its impossible to build. i get #import <Paystack/Paystack.h> file not found.

**Comment by tolu360** [comment]
Hi!

Which version of the library are you working with and how did you install the Paystack iOS SDK?

**Comment by gbenga504** [comment]
I am using the 3.1.4 version of the library. For installation, following the procedure in your docs failed, so i had to do it the ios way. I download the latest version of the framework zip file from your ios repo, then added it to the Frameworks folder on xcode, also made sure it was linked in *Link and Binaries*, then made sure that the search path pointed to my IOS folder so that the framework folder can be located.


Built successfully, but the app closes almost immediately after builiding

**Comment by gbenga504** [comment]
i updated to v3.3.0, and i got it working. For cocoapods, you missed out the part of running *cd ios && pod install* from the project's root directory. This is quite important especially to beginners new to ios in react-native and cocoapods as well..... 

Do you mind if i help contribute to your docs ?

**Comment by gbenga504** [comment]
Thanks ... would check the updated docs and add whats missing .. Would close this issue for now... Thanks for the quick response.

**Comment by Michaelvons** [comment]
Hello guys,
Previous hints did not work for me.
 file still not found

**Comment by Michaelvons** [comment]
![screen shot 2019-02-26 at 4 09 53 pm](https://user-images.githubusercontent.com/17091410/53423143-1983be80-39e1-11e9-8f86-f86c48effd9a.png)
![screen shot 2019-02-26 at 4 09 43 pm](https://user-images.githubusercontent.com/17091410/53423163-243e5380-39e1-11e9-9fa3-5531d632d3c4.png)

**Comment by tolu360** [comment]
@Michaelvons  Please ensure you are using the latest version of this library and opt for the [CocoaPod flow](https://github.com/tolu360/react-native-paystack#install-paystack-ios-sdk-via-cocoapods-option-1---recommended-only-available-in-v33) to install on iOS - it is less prone to build errors
