### ISSUE TITLE
How can I integrate react-native-paystack to an e-commerce app.

### ISSUE THREAD

**Issue by jerryheir** [tolu360/react-native-paystack#23]
How can I integrate react-native-paystack to an e-commerce type of app where I take the users card details at sign up and can charge them with a token whenever they make a purchase ???? From what I see in the repo, I have to initialize transaction before send card details.
Please its urgent.
HELP

**Comment by jerryheir** [comment]
My company executives met with yours and was told paystack can do this but I can't find this in this endpoint or on the paystack docs

**Comment by steveamaza** [comment]
Hi Jeremiah, this is a third party library and you can only get answers concerning the library here. Please email support@paystack.com for questions concerning the Paystack API

**Comment by jerryheir** [comment]
I found out one can be charged with the authorization_code that was gotten after verification of first transaction. Tested that and it worked fine
Thats probably something that should be added to this library along side refunds

**Comment by jerryheir** [comment]
Thank you Steve
