### ISSUE TITLE
Cannot build ejected expo project after including react-native-paystack

### ISSUE THREAD

**Issue by davidteejay** [tolu360/react-native-paystack#24]
I needed to setup payment on my app I built using expo so I ejected the project and installed react-native-paystack and linked it, and it keeps throwing this error when I try to build

![screenshot from 2018-11-30 14-48-35](https://user-images.githubusercontent.com/19327099/49293002-1430d980-f4af-11e8-9389-547a11079ed4.png)

I've tried searching on how to fix it, but to no avail.

**Comment by lordkiz** [comment]
Have you tried `configurations.all {
        exclude module: 'okhttp-ws'
}` ?

**Comment by tolu360** [comment]
Please see #38, follow the guides and only re-submit your issue if it persists thereafter. Cheers!
