### ISSUE TITLE
you should call init first higer up your code https://github.com/tolu360/react-native-paystack#3-usage

### ISSUE THREAD

**Issue by adeojoemmanuel** [tolu360/react-native-paystack#25]
i get the error

 `you should call init first higer up your code https://github.com/tolu360/react-native-paystack#3-usagei get this error "`

even after calling 

`RNPaystack.init({ publicKey: 'pk_live_7df3a55391cd5a9dc3fe2eeb27a20d3d295feb0d' }); `

right benit my import

**Comment by samie820** [comment]
Hi, please can you show the full .js file where you are calling RNPaystack.init, the issue might be where you are calling it from

**Comment by onyiiamala** [comment]
I did not call

**Comment by hammedismail54** [comment]
Helo pls I have issue on dis help me resolve it
i get the error

`you should call init first higer up your code https://github.com/tolu360/react-native-paystack#3-usagei get this error 
![screenshot_2019-02-02-21-32-35](https://user-images.githubusercontent.com/47283284/52466333-43845680-2b82-11e9-8c75-0ffd9685cb10.jpeg)

**Comment by samie820** [comment]
> Helo pls I have issue on dis help me resolve it
> i get the error
> 
> `you should call init first higer up your code https://github.com/tolu360/react-native-paystack#3-usagei get this error
> ![screenshot_2019-02-02-21-32-35](https://user-images.githubusercontent.com/47283284/52466333-43845680-2b82-11e9-8c75-0ffd9685cb10.jpeg)

Hi @hammedismail54, Can you share a screenshot of where you are calling ```RNPaystack.init({ publicKey: 'YOUR_PUBLIC_KEY_HERE' });```?

**Comment by samie820** [comment]
> I did not call
Hi @onyiiamala, You should actually, when using the library you have to first call ```RNPaystack.init({ publicKey: 'YOUR_PUBLIC_KEY_HERE' });``` higher up in your codebase (maybe in your `componentDidMount` or your `constructor`)

**Comment by hammedismail54** [comment]
Hw do I call RNPaystack.init

**Comment by onyiiamala** [comment]
How do i call init

**Comment by onyiiamala** [comment]
How can i get the loan without calling init because i don't even know how to call init

**Comment by samie820** [comment]
Step 1: Create a JS file and paste the JS class below
```javascript
import RNPaystack from 'react-native-paystack';

/**
 * This class handles all implementation details used to communicate with paystack
 * @class
 * @param  {} onSuccessFunction Callback function to be called when the transaction and verification is successful
 * @param  {} onErrorFunction Callback function to be called when the transaction and/or verrification fails
 */
export class Paystack {
  constructor(onSuccessFunction, onErrorFunction, sandboxMode = false) {
    this.onSuccessFunction = onSuccessFunction;
    this.onErrorFunction = onErrorFunction;
    RNPaystack.init({
      publicKey: '<ENTER_PUBLIC_KEY_FROM_PAYSTACK_HERE>',
    });
    this.sandboxMode = sandboxMode;
  }

  // function that calls the paystack verification endpoint
  verifyTransaction = (referenceID) => {
    fetch('<PAYSTACK_VERIFICATION_URL_WITH_REFERENCE_ID>', {
      headers: { <read paystack documentattion to know which header to use here >},
    })
      .then(responsePlain => responsePlain.json())
      .then((response) => {
        const { data } = response;
        if (response.status && data.status === 'success') {
          this.onSuccessFunction(response);
        } else {
          this.onErrorFunction(response);
        }
      })
      .catch(error => this.onErrorFunction(error));
  };

  // removes object values with empty strings
  cleanObjectPayload = (payload) => {
    const keys = Object.keys(payload);
    const payloadToSend = {};
    keys.forEach((key) => {
      if (payload[key] !== '') {
        payloadToSend[key] = payload[key];
      }
    });
    return payloadToSend;
  };

  // function that actually charges the card
  chargeCard({
    cardNumber = '',
    expiryMonth = '',
    expiryYear = '',
    cvc = '',
    email = '',
    amountInKobo = '',
    subAccount = '',
  } = {}) {
    const inputToSend = this.cleanObjectPayload({
      cardNumber: cardNumber,
      expiryMonth,
      expiryYear,
      cvc,
      email,
      amountInKobo,
      subAccount,
    });

    console.log(inputToSend);
    RNPaystack.chargeCard(inputToSend)
      .then((response) => {
        if (this.sandboxMode) {
          this.onSuccessFunction(response);
        } else {
          this.verifyTransaction(response.reference);
        }
      })
      .catch((error) => {
        this.onErrorFunction(error);
      });
  }
}

export default Paystack;

```

Then use it like below in your React class:
```javascript
  constructor(props) {
    super(props);
    this.paystack = new PaystackService(this.onSuccess, this.onError, true);
  }

  onSuccess = (data) => {
 // function to run if the transaction is successful
  };

  onError = (error) => {
 // handle the error if the payment fails
  };

  handlePayment = () => {
    this.paystack.chargeCard({
      cardNumber: 3222333300987776,
      expiryMonth: 12,
      expiryYear: 30,
      cvc: 110,
      email: '<email address>',
      amountInKobo: 5000000,
    });
  };


```

**Comment by oseme2** [comment]
I don't even understand what to do

**Comment by oseme2** [comment]
Because I got the same init error

**Comment by oseme2** [comment]
Where do I create js

**Comment by samie820** [comment]
> Where do I create js
Wherever you want, you can place it in any folder within your project and import it into where you want to use it

**Comment by oseme2** [comment]
Good day, i actually applied for a loan on soft cash and it came up so how
do i use it on the app

**Comment by oseme2** [comment]
can you please help me with this?

**Comment by oseme2** [comment]
please can i get a step by step on how to go about this?

**Comment by steveamaza** [comment]
> Good day, i actually applied for a loan on soft cash and it came up so how do i use it on the app

@oseme2 I don't see how this is relevant to this library. Please reach out to soft cash

**Comment by steveamaza** [comment]
@hammedismail54 
@oseme2 
@onyiiamala 

This is a library for developers integrating Paystack not for customers of a merchant using Paystack. Please reach out to the support team of the business you are trying to get a loan from so they can help you. This discussion is for developers

**Comment by oseme2** [comment]
okay sir/ma

**Comment by onyiiamala** [comment]
I need a loan from your company, but each time i applied, i always receive increase your Init code. Please what does that stands for?

**Comment by onyiiamala** [comment]
I need a loan from your company, but each time i applied, i always receive increase your Init code. Please what does that stands for?

**Comment by steveamaza** [comment]
@tolu360 can you please call this issue :)
@onyiiamala please email support@paystack.com

**Comment by twenty9canmakeit** [comment]
Am getting issue on my softcash app when applying for a load after filling every details its indicating I should call init can someone explain to me better how I can go about it.

**Comment by tolu360** [comment]
Hi Softcash Dev, please update your app and stop showing these errors to your users - they are mainly just for your benefits. Thank you!
