### ISSUE TITLE
styling the number pad and webview window

### ISSUE THREAD

**Issue by Michaelvons** [tolu360/react-native-paystack#27]
How do I style the number pad and webView window? It doesn't really look so great. I would like to give it some custom styling.

**Comment by tolu360** [comment]
Hello Michael, I am afraid custom look and feel is not exactly supported by the Paystack SDKs ([Android](https://github.com/PaystackHQ/paystack-android) and [iOS](https://github.com/PaystackHQ/paystack-ios)) at the moment. Please follow up with the folks at Paystack (try their Slack channel or via email) and you can re-open this issue if and when UI customizations are supported by the SDKs.

Cheers!
