### ISSUE TITLE
Conflicts in okhttp versions in Paystack SDK and React Native 0.58+

### ISSUE THREAD

**Issue by nwaughachukwuma** [tolu360/react-native-paystack#28]
Hi @tolu360. Please this package breaks when building a React Native 0.58.x App with following errors
`
Could not resolve com.squareup.okhttp3:okhttp:3.12.1 required by react-native@0.58.x
`. Any plans to upgrade it?

**Comment by christiandrey** [comment]
A conflict between versions of dependencies between the underlying Paystack Android SDK and React Native could cause an issue like this. A workaround would be to add the following code block to the `android/build.gradle` file, just after `allProjects`.

```java
subprojects {
    project.configurations.all {
        resolutionStrategy.eachDependency { details ->
            if (details.requested.group == 'com.android.support' && !details.requested.name.contains('multidex')) {
                details.useVersion "28.0.0"
            }

            if (details.requested.group == 'com.squareup.okhttp3' && !details.requested.name.contains('multidex')) {
                details.useVersion "3.12.1"
            }

            if (details.requested.group == 'com.squareup.okio' && !details.requested.name.contains('multidex')) {
                details.useVersion "1.15.0"
            }
        }
    }
}
```
This solution also works for the newly released RN v0.59. I hope it helps!

**Comment by nwaughachukwuma** [comment]
Alright @christiandrey thanks so much

**Comment by nkorojoseph** [comment]
None of this working

**Comment by nkorojoseph** [comment]
Can someone help with this stuff

**Comment by christiandrey** [comment]
Can you please put up the actual error you're getting here? Might help in tracking down the issue. Thanks.

**Comment by nkorojoseph** [comment]
> Hi @tolu360. Please this package breaks when building a React Native 0.58.x App with following errors
> `Could not resolve com.squareup.okhttp3:okhttp:3.12.1 required by react-native@0.58.x`. Any plans to upgrade it?

exactly something like this

**Comment by nkorojoseph** [comment]
![image](https://user-images.githubusercontent.com/16070025/57840830-4914bc80-77c1-11e9-9b4b-fcaea3c1e183.png)

**Comment by nwaughachukwuma** [comment]
Can you show the contents of your root and app build.gradle files?

**Comment by christiandrey** [comment]
I think the problem could be that you're putting the code block in the wrong file. Please make sure you're putting that code just after `allprojects` in the root `build.gradle` file and not the app `build.gradle` file. 
Here's a screenshot of my root `build.gradle file`.
![image](https://user-images.githubusercontent.com/22384828/57842738-06ed7a00-77c5-11e9-9f32-60271ef2ff74.png)
![image](https://user-images.githubusercontent.com/22384828/57842749-0c4ac480-77c5-11e9-893c-b58e7867ce68.png)

**Comment by nkorojoseph** [comment]
![image](https://user-images.githubusercontent.com/16070025/57843345-030e2780-77c6-11e9-8ee7-66a97dd187b1.png)
![image](https://user-images.githubusercontent.com/16070025/57843402-1faa5f80-77c6-11e9-967a-791124ce7efc.png)

**Comment by nkorojoseph** [comment]
i have put it in the exact location as you said bro, but the error changed to the above screenshot

**Comment by christiandrey** [comment]
Okay, this is a simpler error. You have this issue because the `react-native-paystack` library has specified its `minSdkVersion` as 19 while React Native, by default, specifies it as 16. The library also has specified `android:allowBackup="true"` in its `AndroidManifest.xml` while React Native has specified it by default as `android:allowBackup="false"`. To fix, you should update your `minSdkVersion`, still in the root `build.gradle` file to 19 and set `android:allowBackup="false"` in `AndroidManifest`. Instead, you can install the `react-native-paystack` from a fork I created where i fixed these last two issues in. Do `npm install christiandrey/react-native-paystack` or `yarn add christiandrey/react-native-paystack`, if you you use Yarn, to install from this fork.
Hope that helps!

**Comment by nkorojoseph** [comment]
> AndroidManifest. 
which folder can i locate this

**Comment by nkorojoseph** [comment]
because the one under android-src-main didnt work

**Comment by christiandrey** [comment]
Ideally, it should be the one in `android/src/main`. But if that's not working, you can try installing the package from the fork. It should be a better alternative. Please try that. Thanks!

**Comment by nkorojoseph** [comment]
worked ---
I had to set `android:allowBackup="false"` to 'true ' in the `android/src/main ` . Hope it doesn't mean any security issue

**Comment by christiandrey** [comment]
No, it doesn't have any security implication.`android:allowBackup` only tells the system to include your app when a user is backing up their device.

**Comment by nkorojoseph** [comment]
i was able to compile and my emulator worked fine... Though i have not used any of the api, but great thanks for this.... @christiandrey you are the best..

**Comment by tolu360** [comment]
Great stuff @christiandrey helping out today, cheers! If you added a feature you want me to know about in your fork, I would be happy to receive a PR. 

@nkorojoseph glad you got stuff to work!

**Comment by nkorojoseph** [comment]
hi @tolu360  and @christiandrey, please can you help me with `chargeCard() {

	RNPaystack.chargeCardWithAccessCode({
      cardNumber: '4123450131001381', 
      expiryMonth: '10', 
      expiryYear: '17', 
      cvc: '883',
      accessCode: '2p3j42th639duy4'
    })
	.then(response => {
	  console.log(response); // do stuff with the token
	})
	.catch(error => {
	  console.log(error); // error is a javascript Error object
	  console.log(error.message);
	  console.log(error.code);
	})
	
}`
what this access code is and where to get it.

**Comment by tolu360** [comment]
All these are detailed in the docs, read them carefully [here](https://github.com/tolu360/react-native-paystack#3-usage). And if you have further issues unrelated to the conflict in okhttp library, I would recommend you open a new issue for those. Cheers

**Comment by nkorojoseph** [comment]
> All these are detailed in the docs, read them carefully [here](https://github.com/tolu360/react-native-paystack#3-usage). And if you have further issues unrelated to the conflict in okhttp library, I would recommend you open a new issue for those. Cheers

Ok, thanks....

**Comment by tolu360** [comment]
Please see #38, follow the guides and only re-submit your issue if it persists thereafter. Cheers!
