### ISSUE TITLE
Could not resolve all files for configuration ':react-native-paystack:debugCompileClasspath'.

### ISSUE THREAD

**Issue by ckOfor** [tolu360/react-native-paystack#29]
Android `"react-native": "0.59.2",`

Steps to reproduce
1. Create an RN project
2. run ```npm install react-native-paystack --save```
3. run ```react-native link react-native-paystack ```
4. run ```npm start --reset-cache```
5. run ```yarn run android```

> Task :react-native-paystack:compileDebugRenderscript FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all files for configuration ':react-native-paystack:debugCompileClasspath'.
> Could not resolve com.squareup.okhttp3:okhttp:3.7.0.
  Required by:
      project :react-native-paystack
   > Cannot find a version of 'com.squareup.okhttp3:okhttp' that satisfies the version constraints: 
        Dependency path 'Biscayne:react-native-paystack:unspecified' --> 'com.facebook.react:react-native:0.59.2' --> 'com.squareup.okhttp3:okhttp:3.12.1'
        Dependency path 'Biscayne:react-native-paystack:unspecified' --> 'co.paystack.android:paystack:3.0.10' --> 'com.squareup.okhttp3:okhttp:3.7.0'
        Dependency path 'Biscayne:react-native-paystack:unspecified' --> 'com.facebook.react:react-native:0.59.2' --> 'com.facebook.fresco:imagepipeline-okhttp3:1.10.0' --> 'com.squareup.okhttp3:okhttp:3.10.0'
        Dependency path 'Biscayne:react-native-paystack:unspecified' --> 'com.facebook.react:react-native:0.59.2' --> 'com.squareup.okhttp3:okhttp-urlconnection:3.12.1' --> 'com.squareup.okhttp3:okhttp:3.12.1'
        Dependency path 'Biscayne:react-native-paystack:unspecified' --> 'co.paystack.android:paystack:3.0.10' --> 'com.squareup.retrofit2:retrofit:2.1.0' --> 'com.squareup.okhttp3:okhttp:3.3.0'
        Constraint path 'Biscayne:react-native-paystack:unspecified' --> 'com.squareup.okhttp3:okhttp' strictly '3.7.0' because of the following reason: debugRuntimeClasspath uses version 3.7.0
        Constraint path 'Biscayne:react-native-paystack:unspecified' --> 'com.squareup.okhttp3:okhttp' strictly '3.7.0' because of the following reason: debugRuntimeClasspath uses version 3.7.0
        Constraint path 'Biscayne:react-native-paystack:unspecified' --> 'com.squareup.okhttp3:okhttp' strictly '3.7.0' because of the following reason: debugRuntimeClasspath uses version 3.7.0
        Constraint path 'Biscayne:react-native-paystack:unspecified' --> 'com.squareup.okhttp3:okhttp' strictly '3.7.0' because of the following reason: debugRuntimeClasspath uses version 3.7.0

**Comment by steveamaza** [comment]
@ckOfor what version of RN Paystack are you using?

**Comment by ckOfor** [comment]
@steveamaza ```"react-native": "0.59.2",```

**Comment by tolu360** [comment]
This is the same issue as 28, please take a look at the solution [here](https://github.com/tolu360/react-native-paystack/issues/28#issuecomment-472745479) and maybe close this and follow up there instead.

**Comment by ckOfor** [comment]
Thanks @steveamaza and @tolu360
