### ISSUE TITLE
"You must specify a valid amount or plan" Error

### ISSUE THREAD

**Issue by steveamaza** [tolu360/react-native-paystack#3]
Hello,

When I try to charge card using access code, the `catch(error)` function returns,

`{ [Error: You must specify a valid amount or plan] framesToPop: 1, code: 'E_TRANSACTION_ERROR'}
You must specify a valid amount or plan
E_TRANSACTION_ERROR`

This is weird because on initialising a transaction from my server, I get a response. Here is the latest one I got

`{ status: 'success',
    data: 
        { 
            authorization_url: 'https://paystack.com/secure/uyn69yyh2vas156',
            access_code: 'uyn69yyh2vas156',
            reference: '9gsjuq60vw' 
       } 
}`

Please let me know if there is something I am doing wrong.

**Comment by tolu360** [comment]
@steveamaza can't say, for certain, what you are doing wrong, but you just caught an exception from the underlying Paystack SDK with the message 'You must specify a valid amount or plan'.

Please ensure you don't have a key mismatch - ensure you are using the right key pair (test public on app/test secret on server or the live combination) and not the opposite (test/live pair). 

If the exception continues, please buzz the Paystack guys on Slack and remember to mention the exception message.

**Comment by steveamaza** [comment]
Hey @tolu360. I work with Paystack actually :)

Used the other method of charging directly from within app, but using the chargeWithAccessCode method, we can see that the request is not being sent with the accessCode.

When you have time, please take a look. No rush

**Comment by tolu360** [comment]
Oh, you should have said you work with Paystack upfront though!

But that is a `message` from one of your `own exceptions`, you should be able to tell what's up! Lawal pushed some commits on the SDKs lately, don't know if anything was undone by those. Would check when I have some `me` time.

Cheers!

**Comment by steveamaza** [comment]
Lol. My bad. Didn't think it was necessary. Thank you. I'll also inspect
from my end again when I get a better understanding of the library. Thank
you

**Comment by tolu360** [comment]
Also don't think it is necessary - except I thought, for a minute, the issue was a `life-and-death` case :) Let me see what params you are calling the method with though, if you can!

**Comment by steveamaza** [comment]
Lol. For a moment it was an issue of life and death, before I decided to use the other chargeWithCard method. Here is my object
```
chargeCard() {  
    RNPaystack.chargeCardWithAccessCode({
      cardNumber: '4084084084084081', 
      expiryMonth: '10', 
      expiryYear: '20', 
      cvc: '408',
      accessCode: this.access_code
    })
    .then(response => {
      console.log(response); // do stuff with the token
    })
    .catch(error => {
      console.log(error); // error is a javascript Error object
      console.log(error.message);
      console.log(error.code);
    })  
  }
```

**Comment by tolu360** [comment]
@steveamaza - first off, pull in v3.1.4 of this package, then [update Gradle and other dependencies](https://github.com/tolu360/react-native-paystack#more-config-android-v314). Build and profit!!
