### ISSUE TITLE
release build failed

### ISSUE THREAD

**Issue by Dwayne01** [tolu360/react-native-paystack#30]
i keep getting the bellow errors.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-paystack:verifyReleaseResources'.
> java.util.concurrent.ExecutionException: com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed
  /Users/mac/Development/QuickCash/node_modules/react-native-paystack/android/build/intermediates/res/merged/release/values-v28/values-v28.xml:7: error: resource android:attr/dialogCornerRadius not found.
  /Users/mac/Development/QuickCash/node_modules/react-native-paystack/android/build/intermediates/res/merged/release/values-v28/values-v28.xml:11: error: resource android:attr/dialogCornerRadius not found.
  /Users/mac/Development/QuickCash/node_modules/react-native-paystack/android/build/intermediates/res/merged/release/values/values.xml:2647: error: resource android:attr/fontVariationSettings not found.
  /Users/mac/Development/QuickCash/node_modules/react-native-paystack/android/build/intermediates/res/merged/release/values/values.xml:2648: error: resource android:attr/ttcIndex not found.
  error: failed linking references.

**Comment by klazbaba** [comment]
To solve this, got to the build.gradle file of react-native-paystack inside of your node modules folder. Then change compileSdkVersion to 28.

**Comment by neyosoft** [comment]
The version is already in 28.

@Dwayne01 do you get any solution to this?
