### ISSUE TITLE
How we can enable bank transfer option?

### ISSUE THREAD

**Issue by kaydee92** [tolu360/react-native-paystack#32]
Hello
Thanks for this plugin. we have some difficulty to find the option, how to enable bank transfer.
Please reply as soon as possible.
thanks

**Comment by tolu360** [comment]
Hi, the underlying Paystack SDKs ([Android](https://github.com/PaystackHQ/paystack-android) & [iOS](https://github.com/PaystackHQ/paystack-ios)) do not currently support the functionality - hence this library has no such support either. You can ask the Paystack team about it in any of their official communication channels. Cheers!
