### ISSUE TITLE
OTP Screen

### ISSUE THREAD

**Issue by Ifunanyacollins** [tolu360/react-native-paystack#34]
Some card requires OTP to finalize your payment and from your SDK Docs, you didn't show how to handle this scenario.  Please, can you help?

**Comment by tolu360** [comment]
If your user uses a card that requires OTP, the underlying Paystack SDKs
would prompt the user for PINs/ OTPs I believe. You should try any of the
test cards that require PIN/OTP in development to see how that works.
Cheers

**Comment by Ifunanyacollins** [comment]
Yeah, I get this input screen to put in my pin and after that, the transaction fails (When I use a real card). I tried all the test card that requires OTP/PIN and it failed.

Thanks in advance.

**Comment by tolu360** [comment]
Check to make sure your transactions are not failing for other reasons.
Check to be sure you are using test keys with test cards and live keys with
live cards - you cannot mix and match. Try a test card that does not
require PIN/OTP and ensure the transaction is successful, hence
establishing the failures are really down to PINs. Rule out other issues
and keep this open if it does persist afterwards.

**Comment by Ifunanyacollins** [comment]
Test cards that do not require OTP / PIN work but test card that requires that fails (It doesn't show me a field to fill the PIN/OTP ). I tired the test card that simulates bank authorization it pops up an empty modal and afterward charged the card.

**Comment by Dwayne01** [comment]
@tolu360 i have this problem too. test card without otp works but test card with otp is failing.

**Comment by Dwayne01** [comment]
@Ifunanyacollins where you able to find a solution?

**Comment by steveamaza** [comment]
@Ifunanyacollins can you share the OTP card you used that didn't work?

**Comment by Ifunanyacollins** [comment]
Card Number: 5060 6666 6666 6666 666 (Verve)
Expiry Date: any date in the future
CVV: 123
PIN: 1234
OTP: 123456

**Comment by Ifunanyacollins** [comment]
Card Number: 408 408 0000000 409
Expiry Date: any date in the future
CVV: 000

This pop up some kind of blank modal, I am assuming this modal is meant to have input fields to collect OTP but it is blank.

**Comment by tolu360** [comment]
> Card Number: 5060 6666 6666 6666 666 (Verve)
> Expiry Date: any date in the future
> CVV: 123
> PIN: 1234
> OTP: 123456

You should see similar OTP/PIN screens on Android or iOS if you use the test card you referenced here:

![Screenshot_1567621196](https://user-images.githubusercontent.com/3914854/64283149-c6ba2f00-cf4e-11e9-8895-98a31ebc9f6e.png)

![Screenshot_1567615775](https://user-images.githubusercontent.com/3914854/64283174-d5a0e180-cf4e-11e9-888c-b220c584b465.png)

You may want to try again on the latest release - v3.4.0 though, see #38 for more info.

Cheers!
