### ISSUE TITLE
'Paystack/Paystack.h' file not found

### ISSUE THREAD

**Issue by lucasdozie** [tolu360/react-native-paystack#37]
Hi Tolu,
please help me attend to this.

This error has been pop up for a while now, I tried a all the installation method all to no avail

#import <Paystack/Paystack.h>

**Comment by lucasdozie** [comment]
Is this package no longer support or what?

**Comment by tolu360** [comment]
Please see #38, follow the guides and only re-submit your issue if it persists thereafter. Cheers!
