### ISSUE TITLE
Null is not an object

### ISSUE THREAD

**Issue by ckOfor** [tolu360/react-native-paystack#39]
![Simulator Screen Shot - iPhone X - 2019-10-16 at 00 07 06](https://user-images.githubusercontent.com/36486441/66876942-84532b80-efab-11e9-8a87-55bdbac9f501.png)

**Comment by ckOfor** [comment]
Should I close this I use RN 0.60.5 cc: @tolu360

**Comment by ckOfor** [comment]
Should I close this I use "react-native": "0.60.5", cc: @tolu360 ?

**Comment by ckOfor** [comment]
Fixed

**Comment by Rana-Muhammad-Amir** [comment]
@ckOfor how you fixed it... i am also facing this issue on IOS android working fine. as my version of react-native is "react-native":"0.60.5"
@tolu360

**Comment by cpmgbenka** [comment]
> Fixed

How was this fixed?
