### ISSUE TITLE
Cannot read property 'chargeCardWithAccessCode' of undefined

### ISSUE THREAD

**Issue by andela-cofor** [tolu360/react-native-paystack#4]
<img width="392" alt="screen shot 2018-01-22 at 8 29 00 pm" src="https://user-images.githubusercontent.com/25608370/35267522-def05714-0026-11e8-9daa-f43e0bebb42d.png">

**Comment by tolu360** [comment]
This error says `RNPaystack` is undefined. Did you forget to link the module to your project by running `react-native link react-native-paystack`? Did forget import `RNPaystack` in your component? Check both and try to build and run again.

If the error persist, show some code snippet from your own component. lets rule out `Js context` errors too.

**Comment by andela-cofor** [comment]
<img width="656" alt="screen shot 2018-01-23 at 11 58 39 am" src="https://user-images.githubusercontent.com/25608370/35272226-d0d1022e-0034-11e8-94e4-7dcbc509423c.png">

**Comment by tolu360** [comment]
So @andela-cofor how did you create your project? `react-native init`? `react-native create-app`? `expo`? Only projects created by `react-native init` are supported out of the box. Projects created by `react-native create-app` can work if you `eject` your project. Projects created by `expo` are **not** supported.

So if you did `react-native init` let me see code snippet from your component where you are trying to use the module.

**Comment by andela-cofor** [comment]
`react-native create-app` and I ejected the project

**Comment by andela-cofor** [comment]
<img width="359" alt="screen shot 2018-01-23 at 12 13 30 pm" src="https://user-images.githubusercontent.com/25608370/35272847-e3153408-0036-11e8-988b-02ef8dd5b825.png">
<img width="499" alt="screen shot 2018-01-23 at 12 13 38 pm" src="https://user-images.githubusercontent.com/25608370/35272853-e7ed73fa-0036-11e8-99b9-b049ac257f6f.png">

**Comment by tolu360** [comment]
You may need to go over your setup again or try to reproduce your error on the [sample app](https://github.com/tolu360/vestarapp) (clone or just download that, edit AppDelegate and AndroidManifest with your Paystack keys and all, then run)

**Comment by andela-cofor** [comment]
So i started the process again and now I have this error 
<img width="910" alt="screen shot 2018-01-22 at 8 01 54 pm" src="https://user-images.githubusercontent.com/25608370/35276085-6d5fb164-0042-11e8-8d25-9fe247e83e18.png">

**Comment by tolu360** [comment]
Hi @andela-cofor, I hope you sorted things out? If you did, you can leave some info to help the next person, stating what you did differently. Cheers!

**Comment by andela-cofor** [comment]
Alright so when I ejected the app, I ejected it as an expo app, expo has issues with linking I guess, I started the app again and I am ejecting it as an ordinary react-native app

**Comment by andela-cofor** [comment]
@tolu360 after praying I figured the answer, Expo has issues lol, I created a new app and went through the process again and it was smooth and successful great job man.

**Comment by enero-o** [comment]
> So @andela-cofor how did you create your project? `react-native init`? `react-native create-app`? `expo`? Only projects created by `react-native init` are supported out of the box. Projects created by `react-native create-app` can work if you `eject` your project. Projects created by `expo` are **not** supported.
> 
> So if you did `react-native init` let me see code snippet from your component where you are trying to use the module.

Hi @tolu360 
Please is this compatible with Expo now ?
I am running an Expo app and want to make use of paystack, but i cant eject the app now
