### ISSUE TITLE
How does this enable mobile users add card on paystack

### ISSUE THREAD

**Issue by salvationarinze** [tolu360/react-native-paystack#48]
Hi, 
Nice package. I wish to know if this library has a way of enabling users add a card of paystack, returning the auth, without storing the users information

**Comment by tolu360** [comment]
Hey Arinze, the straight answer is No! This package does not make possible anything not currently possible via the Paystack native SDKs or the Paystack API. Card tokenization had long been deprecated by the Paystack team. In its stead, what you can do is charge (on your server) your users a minimal (and/or refundable) card enrolment fee, try N5 or N10 calling `chargeCardWithAccessCode` and save (on your server) the auth code returned for the charge, if successful.

**Comment by salvationarinze** [comment]
Thanks man
