### ISSUE TITLE
Error on Charging Card

### ISSUE THREAD

**Issue by steveamaza** [tolu360/react-native-paystack#5]
Hi,

On updating to v3.1.4, a new error (that wasn't there previously) shows on charging a card.

The error is `undefined is not an object (evaluating 'RNPaystackNative.chargeCard')`

This is my code sample

```
return RNPaystack.chargeCard({
      cardNumber: this.state.cardNumber,
      expiryMonth: "02",
      expiryYear: "20",
      cvc: this.state.cvc,
      email: this.state.email,
      amountInKobo: this.state.amount,
    })
```

**Comment by tolu360** [comment]
You may want to look at #4, most especially if you are bootstrapping your project with `create react-native app` or `Expo`. Cheers

**Comment by steveamaza** [comment]
Never mind. Updated my Gradle, synced and synced and everything works fine. Thanks!
