### ISSUE TITLE
AAPT: error: resource attr/foreground

### ISSUE THREAD

**Issue by ckOfor** [tolu360/react-native-paystack#50]
#### VERSION
- React Native: ~0.61.4
- Paystack vaersion: ^3.4.0
- Android gradle: 3.6.3

#### WHAT DID I DO
- Install paystack using yarn
- complete setting on iOS and it works fine
- Did nothing on android because of autolinking and it throws error
- Throws error

#### ERROR MESSAGE
```* What went wrong:
Execution failed for task ':app:processDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed
     /Users/username/.gradle/caches/transforms-2/files-2.1/a87106e7088d5bdb8f21b169b6bd1e33/jetified-pinpad-1.0.1/res/values/values.xml:7:5-161: AAPT: error: resource attr/foreground (aka com.appname/foreground) not found.

     /Users/username/.gradle/caches/transforms-2/files-2.1/a87106e7088d5bdb8f21b169b6bd1e33/jetified-pinpad-1.0.1/res/values/values.xml:7:5-161: AAPT: error: resource attr/foregroundGravity (aka com.appName/foregroundGravity) not found.```

**Comment by Onibenjo** [comment]
i have this issue

**Comment by Onibenjo** [comment]
@tolu360

**Comment by ckOfor** [comment]
@Onibenjo please check [here](https://github.com/PaystackHQ/paystack-android/issues/33#issuecomment-380778284) for the fix.

**Comment by dammyson** [comment]
Add

```
<declare-styleable name="ForegroundView">
    <attr name="foreground" format="color" />
    <attr name="foregroundGravity" format="integer" />
    <attr name="foregroundInsidePadding" format="boolean" />
</declare-styleable>
```


ass attribute in you to the android res/value in the library (node module)

**Comment by neyosoft** [comment]
Create an `attrs.xml` file in the values directory (**/android/app/src/res/values/attr.xml**)

```
<declare-styleable name="ForegroundView">
    <attr name="foreground" format="color" />
    <attr name="foregroundGravity" format="integer" />
    <attr name="foregroundInsidePadding" format="boolean" />
</declare-styleable>
```

**Comment by okechukwu0127** [comment]
I have this same issue. It suddenly started from no were this month.
the **/android/app/src/res/values/attr.xml** file already existing and i even added a new **attrs.xml** file seeing your post and after building, i get the same error.

All the error points to - com.arttitude360.reactnative.rnpaystack

Nothing seems to work for me. 

How can this be fixed please ?

**Comment by okechukwu0127** [comment]
> Create an `attrs.xml` file in the values directory (**/android/app/src/res/values/attr.xml**)
> 
> ```
> <declare-styleable name="ForegroundView">
>     <attr name="foreground" format="color" />
>     <attr name="foregroundGravity" format="integer" />
>     <attr name="foregroundInsidePadding" format="boolean" />
> </declare-styleable>
> ```

Nothing seems to work for me even after following your directions.

What am i not doing right please ?

**Comment by Solomon198** [comment]
@okechukwu0127 i had this same issue for some weeks and the following hack I did fixed it.
 1) Go to your `node_modules` and look for `react-native-paystack/android` folder
 2) Open the `build.gradle` file and change line **47** which contains widget for `pinpad` from `1.0.1` to `1.0.3`
 Seems the widget old version is having compatibility issues. 
 the line looks like this .. 
   change from ...
    implementation 'co.paystack.android.design.widget:pinpad:1.0.1'
    to 
       implementation 'co.paystack.android.design.widget:pinpad:1.0.3'
