### ISSUE TITLE
Stuck on Loading sometimes and generic Error Charging Card message

### ISSUE THREAD

**Issue by aolowude** [tolu360/react-native-paystack#6]
Hi,

I am working with the most recent React Native and the latest version of your package. I'm used t Paystack and it works super well on most of our products, but this is our first "native" implmentation with React Native (usually use the inline version) So I have noticed that in test mode all is well, but when I put in my Live Public Key (in AppDelegate.m) and test with a real card, sometimes it stays loading indefinitely and other times i get a generic 'Error Charging Card Message'
Excerpt of my code below: (note all variables are accurate and it returns a correct error response if the card number or etc is invalid)

import RNPaystack from 'react-native-paystack';

RNPaystack.chargeCard({
          cardNumber: cardNum, 
          expiryMonth: mm, 
          expiryYear: yy, 
          cvc: cvc,
})

// AppDelegate.m
[Paystack setDefaultPublicKey:@"pk_live_MYLIVEKEY"];

So what could be causing the infinite loading? Am I meant to set my secret key somewhere, as I could not find a location for that in the documentation.

**Comment by tolu360** [comment]
Hi @aolowude, so the only time you should get the error message `Error Charging Card Message` is when your card (card params) is declined by Paystack. 

For your live tests, I would suggest you don't mix and match card params, use live and true values throughout the test - real card numbers, expiration dates, cvv and pin/OTP (you may be prompted for OTP).

Both charge methods in this package are async methods, they both return promises but what you do while you wait for responses is totally up to you. Are you showing an activity indicator while waiting for results or what do you mean by infinite loading? Or at what point in the flow do you see one? Try to get screenshots and obscure sensitive info.

**Comment by aolowude** [comment]
Right now I am getting Error charging card even with the test card details, (is it because I had to increase the expiry year to 18 fom 17? If there is another test card, please let me know as all the ones from the Paystack website also didnt work)
I know it has worked before, even live as it asked me for my card OTP etc and went through, but the last 2 days it has not been functional. I have done full live tests with live keys and live card and also test with the details below:
          // cardNumber: '4123450131001381', 
          // expiryMonth: '10', 
          // expiryYear: '18',

**Comment by aolowude** [comment]
This has been resolved. I started fresh again and all was resolved.

**Comment by lordkiz** [comment]
Having exact same issue using this package on ios. Works on android. Infinite load then some generic "error charging card" message.

**Comment by misteryomi** [comment]
Guys, try this:

Edit the RNPaystack.m file under your RNPaystack.xcodeproj. 

Then replace occurrence of this line of code:

```
    UIViewController *rootViewController = [UIApplication sharedApplication].delegate.window.rootViewController;`
```


With:
```

    UIViewController *rootViewController = [UIApplication sharedApplication].delegate.window.rootViewController;

    while (rootViewController.presentedViewController)
    {
        rootViewController = rootViewController.presentedViewController;
    }
    
```
