### ISSUE TITLE
Build failed for ios

### ISSUE THREAD

**Issue by lagosnomad** [tolu360/react-native-paystack#8]
'Paystack/Paystack.h' file not found 

![screen shot 2018-03-12 at 11 08 10 am](https://user-images.githubusercontent.com/8760121/37277757-fcd5d094-25e5-11e8-92d5-d7837b13921a.png)

**Comment by tolu360** [comment]
Please check the [config section](https://github.com/tolu360/react-native-paystack#automatic-ios--android) of the README again. Ensure you have downloaded the [iOS Paystack Framework](https://github.com/PaystackHQ/paystack-ios/releases/) and added same to your project according to the README.

Clean & Build your project again.
