### ISSUE TITLE
Android Release build issue

### ISSUE THREAD

**Issue by aolowude** [tolu360/react-native-paystack#9]
So I have debugged and pinpointed that in Release Mode, react native apps don't compile in release mode, they only work in debug mode.

I tested by removing all the Paystack code and uninstalling and it compiles fine into release mode, but when compiling to release, I had to 
1. Add 'android.enableAapt2=false'
2. It then gives the error 'Error:In <declare-styleable> ForegroundView, unable to find attribute foreground' and we are unable to get past that point.

Please assist.

**Comment by aolowude** [comment]
Specifically, What went wrong:
ERROR: In <declare-styleable> ForegroundView, unable to find attribute foreground
ERROR: In <declare-styleable> ForegroundView, unable to find attribute foregroundGravity
...
Execution failed for task ':app:processReleaseResources'

**Comment by tolu360** [comment]
Grab a shot of your terminal with the full error message and paste that here please. Would need to ascertain it's something for me to help with or something strictly for the guys at Paystack!

**Comment by aolowude** [comment]
Without the line:
android.enableAapt2=false

I get the below:

<img width="321" alt="noaapt2_1" src="https://user-images.githubusercontent.com/1243485/37599049-1a8cb24e-2b84-11e8-8584-4d28c7b71ebb.png">
![noaapt2_2](https://user-images.githubusercontent.com/1243485/37599050-1acad0d8-2b84-11e8-9eff-731b5ef350c4.png)


And when I set android.enableAapt2=false
 I get the below:

![aapt2false_2](https://user-images.githubusercontent.com/1243485/37599144-4adbe8ca-2b84-11e8-89c4-44ce7ca4f8c8.png)
![aapt2false_1](https://user-images.githubusercontent.com/1243485/37599147-4b2329ba-2b84-11e8-8172-83e62351d952.png)

**Comment by issimo** [comment]
+1

**Comment by tolu360** [comment]
The task `app:processReleaseResources` failing has little or nothing to do with this package. Do you have the `loginbtn.png` file in your `Js` bundle? It seems to get missing when you try to make a release build.

Try to recompile doing the following:

- Leave aapt2 in its default value.
- Exit any running instance of the Package manager/Metro Bundler on your terminal.
- Run `cd android && ./gradlew clean`.
- Then try your release build again.

**Comment by aolowude** [comment]
I have indeed tried each of your recommendations and confirmed that the loginbtn.png is indeed there.
I have set aapt2 to true, false and removed it (which was default).

Note, when I removed the react-native-paystack package and then set aapt2 to false, it was able to Successfully compile without any other changes, which is what led me to the conclusion that it was indeed something with the package that was causing the issues.

**Comment by tolu360** [comment]
So I can't reproduce your issue and hence may not be able to help further. It looks simple enough though, as it's just a case of RN asset compilation in release mode.

You can try setting up a new RN project, sample App.js code is just fine to test (don't add your app logic or asset). Add the package, do the linking and just try to make a release mode and see if you can reproduce the issue on this separate build.

**Comment by aolowude** [comment]
Hi,

So yea I just ended up recreating my package and it works fine, I was able to do a live payment with OTP and Pin. 

Many thanks for your work and effort amigo

**Comment by dansmog** [comment]
@aolowude What did you do last?

**Comment by Dwayne01** [comment]
how was this issue resolved @aolowude
